@prefix = {{host}}{{basePath}}
@country_code = no

### Status endpoint
GET {{prefix}}/status

### Country info
GET {{prefix}}/info/{{country_code}}

### Exchange rate
GET {{prefix}}/exchange/{{country_code}}

### Root
GET {{host}}

### Country External API
GET http://129.241.150.113:8080/v3.1/alpha/{{country_code}}

### Currency Exchange API
@currency_code = nok
GET http://129.241.150.113:9090/currency/{{currency_code}}