### Status endpoint
GET {{host}}{{prefix}}/status

### Country info
GET {{host}}{{prefix}}/info/{{country_code}}

### Exchange rate
GET {{host}}{{prefix}}/exchange/{{country_code}}

### Root
GET {{host}}


### Help me
GET {{host}}/countryinfo/v1/info/{{country_code}}